#!/usr/bin/env python3
"""Generate every derived artefact from tokens/colors.json.

Run after changing a colour so the CSS, Sass, swatches, colors.md and the
published page all stay in step:

    python3 tools/build.py
"""
import json, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
P = json.loads((ROOT / "tokens/colors.json").read_text())
GRAYS, REDS, CHART = P["grayScale"], P["redScale"], P["chart"]
PRIMARY_LABELS = {"white": "White", "porcelain": "Porcelain", "silver": "Silver",
                  "concrete": "Concrete", "anthracite": "Anthracite", "graphite": "Graphite",
                  "black": "Black", "binderRed": "BINDER Red", "redDark": "Red Dark"}


def srgb(c):
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hexv):
    h = hexv.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * srgb(r) + 0.7152 * srgb(g) + 0.0722 * srgb(b)


def lstar(hexv):
    y = luminance(hexv)
    return 116 * y ** (1 / 3) - 16 if y > 0.008856 else 903.3 * y


def is_light(hexv):
    return lstar(hexv) > 55


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def refs(v):
    return ", ".join(x for x in (v.get("hks"), v.get("pantone"), v.get("ral")) if x) or "—"


def write(rel, text):
    (ROOT / rel).write_text(text)
    print(f"  {rel}")


# --------------------------------------------------------------- CSS and Sass
def build_css():
    out = [":root {", "  /* BINDER corporate colours — generated by tools/build.py", "",
           "     Nine grays numbered 100 (lightest) to 900 (darkest), the same direction",
           "     as CSS font-weight. White and black sit outside the ramp, as they do in",
           "     Bootstrap and Tailwind — there is no --binder-gray-000. */", ""]
    for row in GRAYS:
        key = f"gray-{row['scale']}" if row["scale"] else slug(row["name"])
        out.append(f"  --binder-{key}: {row['hex']};".ljust(44) + f"/* {row['name']} */")
    out += ["", "  /* Named aliases — same values, easier to say out loud */"]
    out += [f"  --binder-{slug(r['name'])}: var(--binder-gray-{r['scale']});"
            for r in GRAYS if r["scale"]]
    out += ["", "  /* Reds. BINDER Red and Red Dark are brand colours, not ramp steps. */"]
    for row in REDS:
        key = f"red-{row['scale']}" if row["scale"] else slug(row["name"])
        out.append(f"  --binder-{key}: {row['hex']};".ljust(44) + f"/* {row['name']} */")
    out += [f"  --binder-{slug(r['name'])}: var(--binder-red-{r['scale']});"
            for r in REDS if r["scale"]]
    out += ["", "  /* Sustainability topics only */",
            f"  --binder-green: {P['green']['hex']};", "",
            "  /* Chart colours A–L. Use a sequence from chartSequences. */"]
    out += [f"  --binder-chart-{c['key'].lower()}: {c['hex']};" for c in CHART]
    out.append("}")
    write("tokens/colors.css", "\n".join(out) + "\n")


def build_scss():
    out = ["// BINDER corporate colours — generated by tools/build.py", "",
           "// White and black sit outside the ramp, as in Bootstrap.",
           f"$white:      {GRAYS[0]['hex']};"]
    out += [f"$gray-{r['scale']}:   {r['hex']};".ljust(28) + f"// {r['name']}"
            for r in GRAYS if r["scale"]]
    out += [f"$black:      {GRAYS[-1]['hex']};", ""]
    out += [f"${slug(r['name'])}: $gray-{r['scale']};" for r in GRAYS if r["scale"]]
    out += ["", "// Reds"]
    for row in REDS:
        name = f"$red-{row['scale']}:" if row["scale"] else f"${slug(row['name'])}:"
        out.append(name.ljust(13) + f"{row['hex']};".ljust(11) + f"// {row['name']}")
    out += ["", f"$binder-green: {P['green']['hex']};", "", "// Chart colours A–L"]
    out += [f"$chart-{c['key'].lower()}:    {c['hex']};" for c in CHART]
    write("tokens/colors.scss", "\n".join(out) + "\n")


# ------------------------------------------------------------------- swatches
def build_swatch(rows, rel, cell=110, height=104):
    width = cell * len(rows)
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
           f'viewBox="0 0 {width} {height}" role="img">',
           f'<rect width="{width}" height="{height}" fill="#ffffff"/>']
    for i, row in enumerate(rows):
        x, hexv = i * cell, row["hex"]
        label = row.get("name") or row.get("key")
        num = f" {row['scale']}" if row.get("scale") else ""
        out += [f'<rect x="{x+4}" y="4" width="{cell-8}" height="56" fill="{hexv}" '
                f'stroke="#d8d8dd" stroke-width="1"/>',
                f'<text x="{x+cell//2}" y="76" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" '
                f'font-size="11" font-weight="bold" fill="#252527">{label}{num}</text>',
                f'<text x="{x+cell//2}" y="92" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" '
                f'font-size="10" fill="#7a7a82">{hexv}</text>']
    out.append("</svg>")
    write(rel, "\n".join(out) + "\n")


def primary_rows():
    return [{"name": PRIMARY_LABELS[k], "hex": v["hex"], "cmyk": v["cmyk"],
             "scale": v.get("scale"), **v} for k, v in P["primary"].items()]


# ------------------------------------------------------------------ colors.md
def build_markdown():
    md = ["# Colours", "",
          "The BINDER appearance rests on a triad of **black, white and BINDER Red**. Everything",
          "else — the grays, the red shades, the chart colours — supports that triad and must",
          "never dilute its contrast.", "",
          "Machine-readable versions live in [tokens/](tokens/): [`colors.json`](tokens/colors.json),",
          "[`colors.css`](tokens/colors.css) and [`colors.scss`](tokens/colors.scss).", "",
          "## Screen and print are defined separately", "",
          "**Hex values apply to screen, CMYK values apply to print.** The grays carry a slight blue",
          "cast on screen but print as pure K with no CMY component. That is deliberate: converted",
          "exactly, the cast comes to under 6 % cyan, and cyan values that low cannot be reproduced",
          "reliably in offset printing. Use hex on screen and CMYK on paper — do not convert one",
          "into the other.", "",
          "## Primary colours", "", "![Primary colours](assets/primary.svg)", "",
          "| Colour | Hex | CMYK | Print references | Use |", "|---|---|---|---|---|"]
    for k, v in P["primary"].items():
        sc = f" {v['scale']}" if v.get("scale") else ""
        md.append(f"| **{PRIMARY_LABELS[k]}**{sc} | `{v['hex']}` | {v['cmyk']} | {refs(v)} | {v['use']} |")

    md += ["", "## The gray scale", "", "![Gray scale](assets/scale-gray.svg)", "",
           "Each gray has a **name** for talking to people and a **number** for code. The scale runs",
           "100 (lightest) to 900 (darkest) — the same direction as CSS `font-weight`.", "",
           "White and black carry no number. They sit outside the ramp, exactly as `$white` and",
           "`$black` do in Bootstrap and Tailwind: a `0` would read as `#000`, which is black.", "",
           "| Name | Scale | Hex | CMYK | L\\* | Step | Previously |",
           "|---|---|---|---|---|---|---|"]
    prev = None
    for row in GRAYS:
        step = f"{prev - row['lstar']:.1f}" if prev is not None else "—"
        prev = row["lstar"]
        was = row["was"] or "**new**"
        if row["name"] == row.get("was"):
            was = "unchanged"
        md.append(f"| {row['name']} | {row['scale'] or '—'} | `{row['hex']}` | {row['cmyk']} "
                  f"| {row['lstar']} | {step} | {was} |")

    md += ["", "L\\* is perceived lightness. The ramp is deliberately **denser at the light end**:",
           "pale background tones get used over large areas, where small differences matter. The",
           "darker half steps more widely, because the eye separates dark tones less well anyway.", "",
           "### What changed in 2026-01", "",
           "- **Pearl `#e6e6e9` added.** `#f4f4f5` sits only 3.8 L\\* from white and was often too",
           "  faint to read as a surface, while `#d8d8dd` was already noticeably grey.",
           "- **Anthracite `#404043` added.** Between Basalt and Graphite the ramp jumped 23.6 L\\*,",
           "  about twice every other step.",
           "- **Charcoal `#1d1d1f` removed.** It sat 3.9 L\\* from Graphite — too close to work as a",
           "  distinct step.",
           "- **Concrete** (formerly Dark Gray) **promoted to a primary colour.** The primaries",
           "  jumped straight from Silver to Graphite with nothing in between.",
           "- **Grays renamed.** In the old scheme `Gray` was lighter than `Medium Gray`, and",
           "  `Darker Gray` was a dead end. Old names are in the table so you can find your way",
           "  around existing files.", "",
           "## The red scale", "", "![Red scale](assets/scale-red.svg)", "",
           "| Name | Scale | Hex | CMYK | Previously |", "|---|---|---|---|---|"]
    for row in REDS:
        was = row["was"] if row["was"] != row["name"] else "unchanged"
        md.append(f"| {row['name']} | {row['scale'] or '—'} | `{row['hex']}` | {row['cmyk']} | {was} |")

    md += ["", "BINDER Red and Red Dark carry no number — they are brand colours, not ramp steps.",
           "`Coral` was previously `Red Bright`, a name that misdescribed it: the tone is not more",
           "vivid than BINDER Red, it is lighter and shifted towards orange.", "",
           "**Red Dark** is the accent alongside BINDER Red — a calm, high-grade colour for",
           "restrained emphasis in graphics and icons, and the mouseover state of a red button.", "",
           "## BINDER Green", "", f"`{P['green']['hex']}` · CMYK {P['green']['cmyk']}", "",
           "Reserved for **sustainability and eco topics** (BINDER goes green). Not a general",
           "purpose accent — using it elsewhere weakens the black/white/red triad.", "",
           "## Chart colours", "", "![Chart colours](assets/scale-chart.svg)", "",
           "| Key | Hex | CMYK |", "|---|---|---|"]
    md += [f"| {c['key']} | `{c['hex']}` | {c['cmyk']} |" for c in CHART]
    md += ["", "### Which colours for how many values", "",
           "Do not pick freely — take the prescribed sequence for the number of values in your",
           "chart. This keeps charts recognisable across all BINDER media.", "",
           "| Values | Sequence |", "|---|---|"]
    for n in sorted(P["chartSequences"], key=int):
        md.append(f"| {n} | {' · '.join(P['chartSequences'][n])} |")
    md += ["", "Text inside charts follows the same rule as everywhere else: never below 6 pt.",
           "See [typography.md](typography.md).", ""]
    write("colors.md", "\n".join(md))


TYPO_SECTION = """<section><h2>Typography</h2>
<p class="lead">The corporate typeface is <strong>FF Meta Pro</strong>, designed by Erik Spiekermann.
It is licensed — every weight has to be bought, and the files are not distributed here. The specimen
below is rendered in a substitute, so it shows hierarchy and proportion rather than the actual letterforms.</p>
<div class="two"><div>
<h3>The family</h3>
<table><tr><th>Family</th><th>Use</th></tr>
<tr><td><strong>Meta Pro</strong></td><td>All standard applications, every weight</td></tr>
<tr><td><strong>Meta Headline OT</strong></td><td>Optional for very large type — trade-show stands, posters</td></tr>
<tr><td><strong>Meta Serif Pro</strong></td><td>Emotional text: quotations, testimonials</td></tr></table>
<h3>Substitutes</h3>
<table><tr><th>Instead of</th><th>Use</th><th>When</th></tr>
<tr><td>Meta Pro</td><td><strong>Arial Unicode MS</strong></td><td>Office applications, Word and PowerPoint templates, Chinese characters</td></tr>
<tr><td>Meta Serif Pro</td><td><strong>Georgia</strong></td><td>Quotations in substitute settings</td></tr></table>
<p style="font-size:14px;color:#7a7a82">Meta Pro is deliberately not used in Office applications —
the Word templates are built on Arial so they render identically on every workstation.</p></div>
<div><h3>Rules</h3><ul class="rules">
<li>Primary text colour is <strong>100&nbsp;% black</strong>. BINDER Red for emphasis, grays to
de-emphasise. White on red or dark backgrounds.</li>
<li><strong>Minimum size 6&nbsp;pt</strong> — including text inside charts and diagrams.</li>
<li>Kerning: <strong>optical</strong>.</li>
<li>Old-style figures in body copy, lining figures in headlines, tabular figures in tables.</li></ul>
<h3>Hierarchy <span class="tag">A4 reading matter; scale other formats proportionally</span></h3>
<table><tr><th>Level</th><th>Weight</th><th>Size / leading</th></tr>
<tr><td>H1</td><td>Bold</td><td>22 / 27.5 pt</td></tr>
<tr><td>Subline</td><td>Light</td><td>22 / 27.5 pt</td></tr>
<tr><td>H2</td><td>Book</td><td>15 / 16.5 pt</td></tr>
<tr><td>H3</td><td>Bold, caps</td><td>10 / 11 pt</td></tr>
<tr><td>H4</td><td>Book</td><td>9 / 11 pt</td></tr>
<tr><td>Body</td><td>Book</td><td>9 / 12 pt</td></tr>
<tr><td>Caption</td><td>Light</td><td>7 / 11 pt</td></tr></table></div></div>
<h3>Specimen</h3>
<div class="specimen">
<div class="sp-h1">Best conditions for your success</div>
<div class="sp-sub">A subline goes into more detail than the headline above it</div>
<div class="sp-h2">Heading level two introduces a section</div>
<div class="sp-h3">Heading level three, set in caps</div>
<div class="sp-body">Body copy carries the argument. Structure the content before you set it: every
topic needs exactly one clearly most important headline, and levels may be skipped where they are not
needed. Content of equal weight gets headlines of equal weight.</div>
<div class="sp-cap">Captions are set only where they add something the image does not already say.</div>
</div></section>"""


LOGO_SECTION = """<section><h2>The red line above titles</h2>
<p class="lead">A short horizontal red line sits directly above main titles — a discreet, distinctive
element that ties visual communication together. All three measurements derive from the font size,
so the rule holds at any scale.</p>
<div class="two"><div><table><tr><th>Property</th><th>Rule</th></tr>
<tr><td>Colour</td><td>BINDER Red</td></tr>
<tr><td>Placement</td><td>Directly above the title, always flush left</td></tr>
<tr><td>Thickness</td><td><strong>0.10 ×</strong> font size</td></tr>
<tr><td>Length</td><td>Width of the <strong>first three letters</strong> of the title</td></tr>
<tr><td>Distance to title</td><td><strong>0.3 ×</strong> font size</td></tr></table>
<p style="font-size:14px;color:#7a7a82">At 50 pt type: thickness 5 pt, distance 16.6 pt.
At 25 pt type: thickness 2.5 pt, distance 8.3 pt.</p></div>
<div><svg viewBox="0 0 380 150" width="100%" style="border:1px solid #d8d8dd;background:#fff"
role="img" aria-label="Diagram of the red line rule">
<rect x="40" y="42" width="52" height="5" fill="#e60000"/>
<text x="40" y="97" font-family="Helvetica,Arial" font-size="42" font-weight="bold" fill="#252527">Incubator</text>
<line x1="40" y1="30" x2="92" y2="30" stroke="#9a9aa1" stroke-width="1"/>
<text x="66" y="25" font-family="Helvetica,Arial" font-size="10" fill="#7a7a82" text-anchor="middle">first 3 letters</text>
<line x1="26" y1="47" x2="26" y2="63" stroke="#9a9aa1" stroke-width="1"/>
<text x="20" y="58" font-family="Helvetica,Arial" font-size="10" fill="#7a7a82" text-anchor="end">0.3 X</text>
<line x1="100" y1="42" x2="118" y2="42" stroke="#9a9aa1" stroke-width="1"/>
<line x1="100" y1="47" x2="118" y2="47" stroke="#9a9aa1" stroke-width="1"/>
<text x="124" y="48" font-family="Helvetica,Arial" font-size="10" fill="#7a7a82">0.10 X</text>
<line x1="290" y1="63" x2="290" y2="97" stroke="#9a9aa1" stroke-width="1"/>
<text x="298" y="84" font-family="Helvetica,Arial" font-size="10" fill="#7a7a82">X = font size</text>
</svg></div></div>
<h2 style="margin-top:44px">Logo</h2>
<p class="lead">The logo files are not in this repository yet — request them from the marketing
department. These rules apply regardless of where you obtained them.</p>
<div class="two"><div><h3>Clear space and position</h3>
<p style="font-size:14px">The measure is <strong>X, the height of the Bildmarke</strong>. Keep
<strong>1.5 × X</strong> clear on all sides — no element may sit inside that zone. Place the logo
<strong>top right, 2 × X from the format edge</strong>. The positioning distance is not the clear
space; observe both.</p>
<svg viewBox="0 0 300 190" width="100%" style="border:1px solid #d8d8dd;background:#fff"
role="img" aria-label="Diagram of logo clear space">
<rect x="1" y="1" width="298" height="188" fill="none" stroke="#d8d8dd"/>
<rect x="168" y="42" width="102" height="44" fill="none" stroke="#e60000" stroke-dasharray="4 3"/>
<rect x="198" y="56" width="42" height="16" fill="#252527"/>
<polygon points="186,56 198,56 192,72" fill="#e60000"/>
<polygon points="174,56 186,56 180,72" fill="#e60000"/>
<line x1="270" y1="20" x2="270" y2="42" stroke="#9a9aa1"/>
<text x="276" y="34" font-family="Helvetica,Arial" font-size="9" fill="#7a7a82">2 X</text>
<text x="219" y="100" font-family="Helvetica,Arial" font-size="9" fill="#e60000" text-anchor="middle">clear space 1.5 X</text>
<line x1="174" y1="80" x2="174" y2="86" stroke="#9a9aa1"/>
<text x="150" y="86" font-family="Helvetica,Arial" font-size="9" fill="#7a7a82" text-anchor="end">X = height</text>
</svg></div>
<div><h3>Minimum sizes</h3>
<table><tr><th>Version</th><th>Minimum</th></tr>
<tr><td>Logo <strong>with</strong> claim</td><td>30 mm</td></tr>
<tr><td>Logo <strong>without</strong> claim</td><td>20 mm</td></tr>
<tr><td>Bildmarke alone</td><td>5 mm</td></tr></table>
<p style="font-size:14px;color:#7a7a82">Below 30 mm logo width, drop the claim — it is no longer legible.</p>
<h3>Never</h3><ul class="rules">
<li>Use the word mark without the Bildmarke</li>
<li>Replace the typeface</li>
<li>Crop, compress, distort or rotate it</li>
<li>Add further elements to it</li>
<li>Recolour it beyond black, white or full colour</li>
<li>Use the Bildmarke as a bullet, watermark or decoration</li></ul></div></div></section>"""


# ------------------------------------------------------------------ docs page
PAGE_CSS = """
:root{--w:#fff;--g100:#f4f4f5;--g300:#d8d8dd;--g500:#9a9aa1;--g600:#7a7a82;--g700:#5a5a5f;--g900:#252527;--red:#e60000}
*{box-sizing:border-box}
body{margin:0;background:var(--g100);color:var(--g900);font:15px/1.6 "Helvetica Neue",Arial,sans-serif;-webkit-font-smoothing:antialiased}
.wrap{max-width:1180px;margin:0 auto;background:var(--w);min-height:100vh;box-shadow:0 0 40px rgba(0,0,0,.07)}
header{padding:56px 44px 40px;border-bottom:1px solid var(--g300)}
.rule{width:58px;height:6px;background:var(--red);margin-bottom:18px}
h1{margin:0;font-size:38px;line-height:1.1;font-weight:700;letter-spacing:-.02em}
header p{margin:12px 0 0;color:var(--g700);font-size:17px;max-width:62ch}
header .meta{margin-top:20px;font-size:13px;color:var(--g600)}
header a{color:var(--red);text-decoration:none;border-bottom:1px solid rgba(230,0,0,.3)}
section{padding:44px}section+section{border-top:1px solid var(--g300)}
h2{font-size:25px;margin:0 0 6px;font-weight:700;letter-spacing:-.01em;position:relative;padding-top:14px}
h2::before{content:"";position:absolute;top:0;left:0;width:2.6ch;height:2.5px;background:var(--red)}
h3{font-size:16px;margin:34px 0 10px;font-weight:700}
.lead{color:var(--g700);margin:0 0 26px;max-width:70ch}
.grid{display:grid;gap:2px;background:var(--g300);border:1px solid var(--g300)}
.c8{grid-template-columns:repeat(8,1fr)}.c11{grid-template-columns:repeat(11,1fr)}
.c5{grid-template-columns:repeat(5,1fr)}.c12{grid-template-columns:repeat(12,1fr)}
.sw{aspect-ratio:1;border:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;
 color:#fff;cursor:pointer;font:inherit;padding:7px;text-align:center;position:relative;transition:transform .18s ease,box-shadow .18s ease}
.sw.light{color:var(--g900)}
.sw:hover{transform:scale(1.09);z-index:5;box-shadow:0 6px 22px rgba(0,0,0,.28)}
.sw .nm{font-size:11.5px;font-weight:700;line-height:1.2}
.sw .n{display:block;font-weight:400;opacity:.72;font-size:10px}
.sw .cd{font-size:9px;opacity:.88;line-height:1.4}
.sw.copied::after{content:"copied";position:absolute;top:5px;right:5px;background:var(--red);color:#fff;font-size:9px;padding:2px 5px;border-radius:2px}
table{border-collapse:collapse;width:100%;font-size:14px;margin:14px 0}
th,td{text-align:left;padding:9px 12px;border-bottom:1px solid var(--g300)}
th{background:var(--g100);font-weight:700;font-size:13px}
code{background:var(--g100);padding:1px 6px;border-radius:3px;font-size:13px}
.note{border-left:4px solid var(--red);background:var(--g100);padding:16px 20px;margin:22px 0;max-width:78ch}
.note strong{display:block;margin-bottom:4px}
.bars{display:flex;align-items:flex-end;gap:4px;height:190px;margin:26px 0 8px}
.bars div{flex:1;border-radius:2px 2px 0 0;position:relative}
.bars span{position:absolute;top:-19px;left:0;right:0;text-align:center;font-size:11px;color:var(--g600)}
.cap{font-size:13px;color:var(--g600);margin-top:6px}
.specimen{border:1px solid var(--g300);padding:30px 34px;margin:16px 0}
.specimen div{margin:0 0 14px}
.sp-h1{font-size:31px;font-weight:700;line-height:1.25}
.sp-sub{font-size:31px;font-weight:300;line-height:1.25;color:var(--g600)}
.sp-h2{font-size:21px;font-weight:400}
.sp-h3{font-size:14px;font-weight:700;text-transform:uppercase;letter-spacing:.07em}
.sp-body{font-size:13px;max-width:62ch}
.sp-cap{font-size:11px;font-weight:300;color:var(--g600)}
.tag{font-size:11px;color:var(--g500);font-weight:400;text-transform:none;letter-spacing:0;margin-left:10px}
.two{display:grid;grid-template-columns:1fr 1fr;gap:30px}
ul.rules{font-size:14px;line-height:1.75;padding-left:20px}
footer{padding:34px 44px 50px;border-top:1px solid var(--g300);font-size:13px;color:var(--g600)}
footer a{color:var(--red)}
.seqrow span{display:inline-block;width:16px;height:16px;margin-right:3px;vertical-align:-3px;border-radius:2px}
@media(max-width:820px){.two{grid-template-columns:1fr}.c11,.c8{grid-template-columns:repeat(4,1fr)}
 .c12{grid-template-columns:repeat(6,1fr)}section{padding:30px 22px}header{padding:38px 22px 30px}h1{font-size:29px}}
"""


def cell(name, hexv, cmyk, scale=None, extra=""):
    cls = "light" if is_light(hexv) else ""
    num = f'<span class="n">{scale}</span>' if scale else ""
    return (f'<button class="sw {cls}" style="background:{hexv}" data-hex="{hexv}">'
            f'<span class="nm">{name}{num}</span>'
            f'<span class="cd">{hexv}<br>{cmyk}{extra}</span></button>')


def build_page():
    h = ['<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">',
         '<meta name="viewport" content="width=device-width,initial-scale=1">',
         '<title>BINDER Corporate Design</title>',
         f'<style>{PAGE_CSS}</style></head><body><div class="wrap">',
         '<header><div class="rule"></div><h1>BINDER Corporate Design</h1>',
         '<p>Colours, typography and logo rules for anyone producing material in the BINDER '
         'design — agencies, partners, suppliers and integrators.</p>',
         '<div class="meta">Version 2026-01 · '
         '<a href="https://github.com/Binder-GmbH/binder-corporate-design">Repository on GitHub</a>'
         ' · Click any colour to copy its hex value</div></header>',
         '<section><h2>The triad</h2><p class="lead">Black, white and BINDER Red produce the '
         'primary BINDER colour impression. This triad is the core of the appearance and a design '
         'element in its own right. Everything else supports it and must never dilute its contrast.</p>',
         '<div class="two"><div><h3>How the three are used</h3><table>',
         '<tr><th>Colour</th><th>Role</th></tr>',
         '<tr><td><strong>White</strong></td><td>Used generously and over large areas: structure, '
         'backgrounds, white space, negative applications. White is what gives the triad its contrast.</td></tr>',
         '<tr><td><strong>Black</strong></td><td>Primary text colour, base for graphics and icons. '
         'Avoid large, full-coverage black areas.</td></tr>',
         '<tr><td><strong>BINDER Red</strong></td><td>The highlight: emphasis in type, graphic '
         'elements, icons, anything that has to stand out.</td></tr></table></div>',
         '<div><h3>Formal language</h3><table><tr><th>Do</th><th>Don\'t</th></tr>',
         '<tr><td>Horizontal and vertical forms</td><td>Organic shapes</td></tr>',
         '<tr><td>Circular elements as accents</td><td>Large diagonal areas or lines</td></tr>',
         '<tr><td>Plenty of white space</td><td>Decorative elements</td></tr>',
         '<tr><td>Clear information hierarchy</td><td>Unusual styling</td></tr>',
         '</table></div></div></section>',
         '<section><h2>Colours</h2><p class="lead">Hex values apply to screen, CMYK values to print.</p>',
         '<h3>Primary colours</h3><div class="grid c8">']
    for k, v in P["primary"].items():
        h.append(cell(PRIMARY_LABELS[k], v["hex"], v["cmyk"], v.get("scale")))
    h.append('</div><table><tr><th>Colour</th><th>Hex</th><th>CMYK</th><th>Print references</th><th>Use</th></tr>')
    for k, v in P["primary"].items():
        h.append(f'<tr><td><strong>{PRIMARY_LABELS[k]}</strong></td><td><code>{v["hex"]}</code></td>'
                 f'<td>{v["cmyk"]}</td><td>{refs(v)}</td><td>{v["use"]}</td></tr>')
    h.append('</table>')

    h.append('<h3>Gray scale <span class="tag">100 lightest · 900 darkest · white and black sit '
             'outside the ramp</span></h3><div class="grid c11">')
    for row in GRAYS:
        h.append(cell(row["name"], row["hex"], row["cmyk"], row["scale"], f'<br>L* {row["lstar"]}'))
    h.append('</div><div class="bars">')
    for row in GRAYS:
        border = "border:1px solid #d8d8dd;" if row["lstar"] > 90 else ""
        lab = str(row["scale"]) if row["scale"] else ("W" if row["name"] == "White" else "B")
        h.append(f'<div style="height:{max(row["lstar"],3)}%;background:{row["hex"]};{border}">'
                 f'<span>{lab}</span></div>')
    h.append('</div><p class="cap">Bar height = perceived lightness (L*). The ramp is denser at the '
             'light end on purpose: pale surface tones get used over large areas, where small '
             'differences matter.</p>')
    h.append('<table><tr><th>Name</th><th>Scale</th><th>Hex</th><th>CMYK</th><th>L*</th><th>Step</th>'
             '<th>Previously</th></tr>')
    prev = None
    for row in GRAYS:
        step = f"{prev - row['lstar']:.1f}" if prev is not None else "—"
        prev = row["lstar"]
        was = row["was"] or '<strong style="color:#e60000">new</strong>'
        if row["name"] == row.get("was"):
            was = "unchanged"
        h.append(f'<tr><td><strong>{row["name"]}</strong></td><td>{row["scale"] or "—"}</td>'
                 f'<td><code>{row["hex"]}</code></td><td>{row["cmyk"]}</td><td>{row["lstar"]}</td>'
                 f'<td>{step}</td><td>{was}</td></tr>')
    h.append('</table>')
    h.append('<div class="note"><strong>Hex is for screen, CMYK is for print — do not convert between '
             'them.</strong> The grays carry a slight blue cast on screen but print as pure K with no '
             'CMY component. That is deliberate: converted exactly, the cast comes to under 6&nbsp;% '
             'cyan, and cyan values that low cannot be reproduced reliably in offset printing.</div>')
    h.append('<div class="note"><strong>White and black carry no number.</strong> They sit outside the '
             'ramp, exactly as <code>$white</code> and <code>$black</code> do in Bootstrap and Tailwind. '
             'A <code>0</code> would read as <code>#000</code> — which is black.</div>')

    h.append('<h3>Red scale <span class="tag">BINDER Red and Red Dark are brand colours, not ramp '
             'steps</span></h3><div class="grid c5">')
    for row in REDS:
        h.append(cell(row["name"], row["hex"], row["cmyk"], row["scale"]))
    h.append('</div>')
    h.append('<h3>BINDER Green <span class="tag">sustainability and eco topics only</span></h3>'
             '<div class="grid c5">')
    h.append(cell("BINDER Green", P["green"]["hex"], P["green"]["cmyk"]))
    h.append('<div style="grid-column:span 4;background:#fff;padding:22px;color:#7a7a82;font-size:14px;'
             'display:flex;align-items:center">Reserved for BINDER goes green. Not a general-purpose '
             'accent — using it elsewhere weakens the black/white/red triad.</div></div>')
    h.append('<h3>Chart colours</h3><div class="grid c12">')
    for c in CHART:
        h.append(cell(c["key"], c["hex"], c["cmyk"]))
    h.append('</div><p class="cap">Do not pick freely — use the prescribed sequence for the number of '
             'values in your chart.</p><table class="seqrow"><tr><th>Values</th><th>Sequence</th></tr>')
    for n in sorted(P["chartSequences"], key=int):
        seq = P["chartSequences"][n]
        sws = "".join(f'<span style="background:'
                      f'{[c["hex"] for c in CHART if c["key"] == k][0]}"></span>' for k in seq)
        h.append(f'<tr><td><strong>{n}</strong></td><td>{sws} &nbsp;{" · ".join(seq)}</td></tr>')
    h.append('</table></section>')

    h.append(TYPO_SECTION)
    h.append(LOGO_SECTION)
    h.append('<footer><strong>BINDER GmbH Corporate Design</strong> · Version 2026-01 · '
             '<a href="https://github.com/Binder-GmbH/binder-corporate-design">Repository</a> · '
             '<a href="mailto:marketing@binder-world.com">marketing@binder-world.com</a>'
             '<p>The BINDER name, logo and word/figurative marks are protected trademarks of BINDER '
             'GmbH. These guidelines are published for legitimate use by press, partners, suppliers '
             'and integrators. They transfer no rights in the marks themselves.</p></footer></div>'
             '<script>document.querySelectorAll(".sw").forEach(function(b){'
             'b.addEventListener("click",function(){navigator.clipboard.writeText(b.dataset.hex);'
             'b.classList.add("copied");setTimeout(function(){b.classList.remove("copied")},1100);});'
             '});</script></body></html>')
    write("docs/index.html", "\n".join(h))


def main():
    print("Generating from tokens/colors.json:")
    build_css()
    build_scss()
    build_swatch(GRAYS, "assets/scale-gray.svg")
    build_swatch(REDS, "assets/scale-red.svg")
    build_swatch(CHART, "assets/scale-chart.svg", cell=76)
    build_swatch(primary_rows(), "assets/primary.svg")
    build_markdown()
    build_page()


if __name__ == "__main__":
    main()
