#!/usr/bin/env python3
"""Generate the derived artefacts from tokens/colors.json.

Run after changing a value so the CSS, Sass, swatches, colors.md and the
published page stay in step:

    python3 tools/build.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
P = json.loads((ROOT / "tokens/colors.json").read_text())
PRIMARY = P["primary"]
LABELS = {"binderRed": "BINDER Red", "black": "Black", "white": "White", "redDark": "Red Dark"}


def srgb(c):
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def lstar(hexv):
    h = hexv.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    y = 0.2126 * srgb(r) + 0.7152 * srgb(g) + 0.0722 * srgb(b)
    return 116 * y ** (1 / 3) - 16 if y > 0.008856 else 903.3 * y


def is_light(hexv):
    return lstar(hexv) > 55


def refs(v):
    return ", ".join(x for x in (v.get("hks"), v.get("pantone"), v.get("ral")) if x) or "—"


def write(rel, text):
    (ROOT / rel).write_text(text)
    print(f"  {rel}")


def build_css():
    o = [":root {", "  /* BINDER corporate colours — generated by tools/build.py */", "",
         "  /* Primary */"]
    for k, v in PRIMARY.items():
        name = {"binderRed": "red", "redDark": "red-dark", "black": "black", "white": "white"}[k]
        o.append(f"  --binder-{name}: {v['hex']};".ljust(38) + f"/* {LABELS[k]} */")
    o += ["", "  /* Red shades */"]
    o += [f"  --binder-red-{i}: {r['hex']};" for i, r in enumerate(P["redShades"], 1)]
    o += ["", "  /* Black shades, by print K value */"]
    o += [f"  --binder-gray-{r['cmyk'].split('/')[-1]}: {r['hex']};" for r in P["blackShades"]]
    o += ["", "  /* Sustainability topics */", f"  --binder-green: {P['green']['hex']};",
          "", "  /* Chart colours A–L */"]
    o += [f"  --binder-chart-{c['key'].lower()}: {c['hex']};" for c in P["chart"]]
    o.append("}")
    write("tokens/colors.css", "\n".join(o) + "\n")


def build_scss():
    o = ["// BINDER corporate colours — generated by tools/build.py", "", "// Primary"]
    for k, v in PRIMARY.items():
        name = {"binderRed": "red", "redDark": "red-dark", "black": "black", "white": "white"}[k]
        o.append(f"$binder-{name}:".ljust(20) + f"{v['hex']};".ljust(11) + f"// {LABELS[k]}")
    o += ["", "// Red shades"]
    o += [f"$binder-red-{i}:".ljust(20) + f"{r['hex']};" for i, r in enumerate(P["redShades"], 1)]
    o += ["", "// Black shades, by print K value"]
    o += [f"$binder-gray-{r['cmyk'].split('/')[-1]}:".ljust(20) + f"{r['hex']};"
          for r in P["blackShades"]]
    o += ["", f"$binder-green:".ljust(20) + f"{P['green']['hex']};", "", "// Chart colours A–L"]
    o += [f"$binder-chart-{c['key'].lower()}:".ljust(20) + f"{c['hex']};" for c in P["chart"]]
    write("tokens/colors.scss", "\n".join(o) + "\n")


def build_swatch(rows, rel, cell=110, height=104):
    width = cell * len(rows)
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
         f'viewBox="0 0 {width} {height}" role="img">',
         f'<rect width="{width}" height="{height}" fill="#ffffff"/>']
    for i, row in enumerate(rows):
        x, hexv = i * cell, row["hex"]
        label = row.get("label") or row.get("key") or ""
        o += [f'<rect x="{x+4}" y="4" width="{cell-8}" height="56" fill="{hexv}" '
              f'stroke="#cdcdcd" stroke-width="1"/>',
              f'<text x="{x+cell//2}" y="76" text-anchor="middle" '
              f'font-family="Arial,Helvetica,sans-serif" font-size="11" font-weight="bold" '
              f'fill="#000000">{label}</text>',
              f'<text x="{x+cell//2}" y="92" text-anchor="middle" '
              f'font-family="Arial,Helvetica,sans-serif" font-size="10" fill="#737373">{hexv}</text>']
    o.append("</svg>")
    write(rel, "\n".join(o) + "\n")


def build_markdown():
    md = ["# Colours", "",
          "The BINDER appearance rests on a triad of **black, white and BINDER Red**. This triad is",
          "the core of the corporate design and a primary design element in its own right. The",
          "shades support it and must never dilute its contrast.", "",
          "Machine-readable versions live in [tokens/](tokens/): [`colors.json`](tokens/colors.json),",
          "[`colors.css`](tokens/colors.css) and [`colors.scss`](tokens/colors.scss).", "",
          "**Hex values apply to screen, CMYK values apply to print.**", "",
          "## Primary colours", "", "![Primary colours](assets/primary.svg)", "",
          "| Colour | Hex | CMYK | Print references |", "|---|---|---|---|"]
    for k, v in PRIMARY.items():
        md.append(f"| **{LABELS[k]}** | `{v['hex']}` | {v['cmyk']} | {refs(v)} |")
    md += ["", "**BINDER Red** is the highlight colour: emphasis in type, graphic elements, icons,",
           "and design elements that need to stand out.", "",
           "**Black** is the primary text colour and the base for graphics and icons. Avoid large,",
           "full-coverage black areas.", "",
           "**White** is used generously and over large areas: for structure, as background colour",
           "for white space, and as the design colour in negative applications. White is what gives",
           "the triad its contrast.", "",
           "**Red Dark** sets restrained accents alongside BINDER Red — in graphics, icons, and as",
           "the mouseover state of a red button on the web.", "",
           "## Shades", "",
           "Available in reduced use for graphic elements. Take care that they do not weaken the",
           "high-contrast impression of the black/white/red triad.", "",
           "### Red", "", "![Red shades](assets/shades-red.svg)", "",
           "| Hex | CMYK | RGB |", "|---|---|---|"]
    md += [f"| `{r['hex']}` | {r['cmyk']} | {r['rgb']} |" for r in P["redShades"]]
    md += ["", "### Black", "", "![Black shades](assets/shades-black.svg)", "",
           "| Hex | CMYK | RGB |", "|---|---|---|"]
    md += [f"| `{r['hex']}` | {r['cmyk']} | {r['rgb']} |" for r in P["blackShades"]]
    md += ["", "## BINDER Green", "",
           f"`{P['green']['hex']}` · CMYK {P['green']['cmyk']}", "",
           "For **sustainability and eco topics** (BINDER goes green).", "",
           "## Chart colours", "", "![Chart colours](assets/chart.svg)", "",
           "| Key | Hex | CMYK | RGB |", "|---|---|---|---|"]
    md += [f"| {c['key']} | `{c['hex']}` | {c['cmyk']} | {c['rgb']} |" for c in P["chart"]]
    md += ["", "### Which colours for how many values", "",
           "Do not pick freely — take the prescribed sequence for the number of values in your",
           "chart. This keeps charts recognisable across all BINDER media.", "",
           "| Values | Sequence |", "|---|---|"]
    md += [f"| {n} | {' · '.join(P['chartSequences'][n])} |"
           for n in sorted(P["chartSequences"], key=int)]
    md += ["", "Text inside charts follows the same rule as everywhere else: never below 6 pt.",
           "See [typography.md](typography.md).", ""]
    write("colors.md", "\n".join(md))


def cell(label, hexv, cmyk, extra=""):
    cls = "light" if is_light(hexv) else ""
    return (f'<button class="sw {cls}" style="background:{hexv}" data-hex="{hexv}">'
            f'<span class="nm">{label}</span>'
            f'<span class="cd">{hexv}<br>{cmyk}{extra}</span></button>')


PAGE_CSS = """
:root{--w:#fff;--g10:#f0f0f0;--g25:#cdcdcd;--g45:#969696;--g65:#737373;--red:#e60000;--k:#000}
*{box-sizing:border-box}
body{margin:0;background:var(--g10);color:var(--k);font:15px/1.6 "Source Sans 3","Helvetica Neue",Arial,sans-serif}
.wrap{max-width:1180px;margin:0 auto;background:var(--w);min-height:100vh;box-shadow:0 0 40px rgba(0,0,0,.07)}
header{padding:56px 44px 40px;border-bottom:1px solid var(--g25)}
.rule{width:58px;height:6px;background:var(--red);margin-bottom:18px}
h1{margin:0;font-size:38px;line-height:1.1;font-weight:600;letter-spacing:-.02em}
header p{margin:12px 0 0;color:var(--g65);font-size:17px;max-width:62ch}
header .meta{margin-top:20px;font-size:13px;color:var(--g65)}
header a{color:var(--red);text-decoration:none;border-bottom:1px solid rgba(230,0,0,.3)}
section{padding:44px}section+section{border-top:1px solid var(--g25)}
h2{font-size:25px;margin:0 0 6px;font-weight:600;letter-spacing:-.01em;position:relative;padding-top:14px}
h2::before{content:"";position:absolute;top:0;left:0;width:2.6ch;height:2.5px;background:var(--red)}
h3{font-size:16px;margin:34px 0 10px;font-weight:600}
.lead{color:var(--g65);margin:0 0 26px;max-width:70ch}
.grid{display:grid;gap:2px;background:var(--g25);border:1px solid var(--g25)}
.c4{grid-template-columns:repeat(4,1fr)}.c3{grid-template-columns:repeat(3,1fr)}
.c12 .sw{height:96px}.c12 .sw .cd{font-size:8.5px}
.c12{grid-template-columns:repeat(12,1fr)}
.sw{height:132px;border:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;
 color:#fff;cursor:pointer;font:inherit;padding:8px;text-align:center;position:relative;transition:transform .18s ease}
.sw.light{color:var(--k)}
.sw:hover{transform:scale(1.06);z-index:5;box-shadow:0 6px 22px rgba(0,0,0,.28)}
.sw .nm{font-size:12px;font-weight:600;line-height:1.2}
.sw .cd{font-size:9.5px;opacity:.88;line-height:1.4}
.sw.copied::after{content:"copied";position:absolute;top:6px;right:6px;background:var(--red);color:#fff;font-size:9px;padding:2px 5px;border-radius:2px}
table{border-collapse:collapse;width:100%;font-size:14px;margin:14px 0}
th,td{text-align:left;padding:9px 12px;border-bottom:1px solid var(--g25)}
th{background:var(--g10);font-weight:600;font-size:13px}
code{background:var(--g10);padding:1px 6px;border-radius:3px;font-size:13px}
.note{border-left:4px solid var(--red);background:var(--g10);padding:16px 20px;margin:22px 0;max-width:78ch}
.note strong{display:block;margin-bottom:4px}
.specimen{border:1px solid var(--g25);padding:30px 34px;margin:16px 0}
.specimen div{margin:0 0 14px}
.tag{font-size:11px;color:var(--g45);font-weight:400;margin-left:10px}
.two{display:grid;grid-template-columns:1fr 1fr;gap:30px}
ul.rules{font-size:14px;line-height:1.75;padding-left:20px}
footer{padding:34px 44px 50px;border-top:1px solid var(--g25);font-size:13px;color:var(--g65)}
footer a{color:var(--red)}
.seqrow span{display:inline-block;width:16px;height:16px;margin-right:3px;vertical-align:-3px;border-radius:2px}
@media(max-width:820px){.two{grid-template-columns:1fr}.c4,.c3{grid-template-columns:repeat(2,1fr)}
 .sw{height:110px}
 .c12{grid-template-columns:repeat(6,1fr)}section{padding:30px 22px}header{padding:38px 22px 30px}h1{font-size:29px}}
"""

RAW = "https://raw.githubusercontent.com/Binder-GmbH/binder-corporate-design/main/logo"


def build_page():
    h = ['<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">',
         '<meta name="viewport" content="width=device-width,initial-scale=1">',
         '<title>BINDER Corporate Design</title>',
         '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
         '<link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300..600'
         '&display=swap" rel="stylesheet">',
         f'<style>{PAGE_CSS}</style></head><body><div class="wrap">',
         '<header><div class="rule"></div><h1>BINDER Corporate Design</h1>',
         '<p>Colours, typography and logo rules for anyone producing material in the BINDER '
         'design — agencies, partners, suppliers and integrators.</p>',
         '<div class="meta"><a href="https://github.com/Binder-GmbH/binder-corporate-design">'
         'Repository on GitHub</a> · Click any colour to copy its hex value</div></header>',
         '<section><h2>The triad</h2><p class="lead">Black, white and BINDER Red produce the '
         'primary BINDER colour impression. This triad is the core of the corporate design and a '
         'primary design element in its own right. Everything else supports it and must never '
         'dilute its contrast.</p><div class="grid c4">']
    for k, v in PRIMARY.items():
        h.append(cell(LABELS[k], v["hex"], v["cmyk"]))
    h.append('</div><table><tr><th>Colour</th><th>Hex</th><th>CMYK</th><th>Print references</th>'
             '<th>Use</th></tr>')
    for k, v in PRIMARY.items():
        h.append(f'<tr><td><strong>{LABELS[k]}</strong></td><td><code>{v["hex"]}</code></td>'
                 f'<td>{v["cmyk"]}</td><td>{refs(v)}</td><td>{v["use"]}</td></tr>')
    h.append('</table>')

    h.append('<h3>Shades <span class="tag">for reduced use in graphic elements — they must not '
             'weaken the triad</span></h3><div class="grid c3">')
    for r in P["redShades"]:
        h.append(cell("", r["hex"], r["cmyk"]))
    h.append('</div><div class="grid c4" style="margin-top:14px">')
    for r in P["blackShades"]:
        h.append(cell("", r["hex"], r["cmyk"]))
    h.append('</div>')
    h.append('<h3>BINDER Green <span class="tag">sustainability and eco topics</span></h3>'
             '<div class="grid c4">')
    h.append(cell("BINDER Green", P["green"]["hex"], P["green"]["cmyk"]))
    h.append('<div style="grid-column:span 3;background:#fff;padding:22px;color:#737373;'
             'font-size:14px;display:flex;align-items:center">For sustainability and eco topics '
             '(BINDER goes green). Not a general-purpose accent.</div></div>')
    h.append('<h3>Chart colours</h3><div class="grid c12">')
    for c in P["chart"]:
        h.append(cell(c["key"], c["hex"], c["cmyk"]))
    h.append('</div><table class="seqrow"><tr><th>Values</th><th>Sequence</th></tr>')
    for n in sorted(P["chartSequences"], key=int):
        seq = P["chartSequences"][n]
        sws = "".join(f'<span style="background:'
                      f'{[c["hex"] for c in P["chart"] if c["key"] == k][0]}"></span>' for k in seq)
        h.append(f'<tr><td><strong>{n}</strong></td><td>{sws} &nbsp;{" · ".join(seq)}</td></tr>')
    h.append('</table></section>')
    h.append(TYPO_SECTION)
    h.append(LOGO_SECTION)
    h.append('<footer><strong>BINDER GmbH Corporate Design</strong> · '
             '<a href="https://github.com/Binder-GmbH/binder-corporate-design">Repository</a> · '
             '<a href="mailto:marketing@binder-world.com">marketing@binder-world.com</a>'
             '<p>The BINDER name, logo and word/figurative marks are protected trademarks of '
             'BINDER GmbH. These guidelines are published for legitimate use by press, partners, '
             'suppliers and integrators. They transfer no rights in the marks themselves.</p>'
             '</footer></div>'
             '<script>document.querySelectorAll(".sw").forEach(function(b){'
             'b.addEventListener("click",function(){navigator.clipboard.writeText(b.dataset.hex);'
             'b.classList.add("copied");setTimeout(function(){b.classList.remove("copied")},1100);'
             '});});</script></body></html>')
    write("docs/index.html", "\n".join(h))


TYPO_SECTION = """<section><h2>Typography</h2>
<p class="lead">The corporate typeface is <strong>Source Sans 3</strong>, designed by Paul D. Hunt.
It is <strong>open source and free to use</strong> — no licence has to be purchased. Get it from
<a href="https://fonts.google.com/specimen/Source+Sans+3">Google Fonts</a>,
<a href="https://fonts.adobe.com/fonts/source-sans">Adobe Fonts</a> or
<a href="https://github.com/adobe-fonts/source-sans">GitHub</a>. This page is set in it.</p>
<div class="two"><div>
<h3>Loading it on the web</h3>
<pre style="background:#f0f0f0;padding:14px;font-size:12px;overflow-x:auto"><code>&lt;link href="https://fonts.googleapis.com/css2?family=
Source+Sans+3:wght@300..600&amp;display=swap" rel="stylesheet"&gt;

font-family: "Source Sans 3", Arial, sans-serif;</code></pre>
<p style="font-size:14px;color:#737373">Weights in use: Light 300, Regular 400, Medium 500,
SemiBold 600.</p>
<h3>Substitutes</h3>
<table><tr><th>Instead of</th><th>Use</th><th>When</th></tr>
<tr><td>Source Sans 3</td><td><strong>Arial Unicode MS</strong></td><td>Office applications and Word
templates; also covers Chinese characters</td></tr>
<tr><td>The serif companion</td><td><strong>Georgia</strong></td><td>Quotations in substitute
settings</td></tr></table>
<h3>Rules</h3><ul class="rules">
<li>Primary text colour is <strong>100&nbsp;% black</strong>. BINDER Red for emphasis, grays to
de-emphasise. White on red or dark backgrounds.</li>
<li><strong>Minimum size 6&nbsp;pt</strong> — including text inside charts and diagrams.</li>
<li>Kerning: <strong>optical</strong>.</li>
<li>Old-style figures in body copy, lining figures in headlines, tabular figures in tables.</li>
</ul></div><div>
<h3>Hierarchy <span class="tag">A4; scale other formats proportionally</span></h3>
<table><tr><th>Level</th><th>Weight</th><th>Size / leading</th></tr>
<tr><td>H1</td><td>SemiBold</td><td>22 / 27.5 pt</td></tr>
<tr><td>Subline</td><td>Light</td><td>22 / 27.5 pt</td></tr>
<tr><td>H2</td><td>Medium</td><td>15 / 16.5 pt</td></tr>
<tr><td>H3</td><td>SemiBold, caps</td><td>10 / 11 pt</td></tr>
<tr><td>H4</td><td>SemiBold</td><td>9 / 11 pt</td></tr>
<tr><td>Body</td><td>Regular</td><td>8 / 11 pt</td></tr>
<tr><td>Lists</td><td>Light</td><td>8 / 11 pt</td></tr>
<tr><td>Captions</td><td>Light</td><td>7 / 11 pt</td></tr>
<tr><td>Running head</td><td>SemiBold + Light</td><td>8 pt, 65&nbsp;% black</td></tr></table>
<p style="font-size:14px;color:#737373"><strong>Exception</strong> — product catalogue and price
list: H1 SemiBold 18 / 22 pt, subline Light 18 / 22 pt.</p></div></div>
<h3>Specimen</h3>
<div class="specimen">
<div style="font-size:31px;font-weight:600;line-height:1.25">Best conditions for your success</div>
<div style="font-size:31px;font-weight:300;line-height:1.25;color:#737373">A subline goes into more
detail than the headline above it</div>
<div style="font-size:21px;font-weight:500">Heading level two introduces a section</div>
<div style="font-size:14px;font-weight:600;text-transform:uppercase;letter-spacing:.07em">Heading
level three, set in caps</div>
<div style="font-size:13px;max-width:62ch">Body copy carries the argument. Structure the content
before you set it: every topic needs exactly one clearly most important headline, and levels may be
skipped where they are not needed.</div>
<div style="font-size:11px;font-weight:300;color:#737373">Captions are set only where they add
something the image does not already say.</div></div></section>"""


LOGO_SECTION = f"""<section><h2>The red line above titles</h2>
<p class="lead">A short horizontal red line sits directly above main titles. All three measurements
derive from the font size, so the rule holds at any scale.</p>
<div class="two"><div><table><tr><th>Property</th><th>Rule</th></tr>
<tr><td>Colour</td><td>BINDER Red</td></tr>
<tr><td>Placement</td><td>Directly above the title, always flush left</td></tr>
<tr><td>Thickness</td><td><strong>0.10 ×</strong> font size</td></tr>
<tr><td>Length</td><td>Width of the <strong>first three letters</strong> of the title</td></tr>
<tr><td>Distance to title</td><td><strong>0.3 ×</strong> font size</td></tr></table>
<p style="font-size:14px;color:#737373">At 50 pt type: thickness 5 pt, distance 16.6 pt.</p></div>
<div><svg viewBox="0 0 380 150" width="100%" style="border:1px solid #cdcdcd;background:#fff"
role="img" aria-label="Diagram of the red line rule">
<rect x="40" y="42" width="52" height="5" fill="#e60000"/>
<text x="40" y="97" font-family="Helvetica,Arial" font-size="42" font-weight="bold"
fill="#000">Incubator</text>
<line x1="40" y1="30" x2="92" y2="30" stroke="#969696"/>
<text x="66" y="25" font-family="Helvetica,Arial" font-size="10" fill="#737373"
text-anchor="middle">first 3 letters</text>
<line x1="26" y1="47" x2="26" y2="63" stroke="#969696"/>
<text x="20" y="58" font-family="Helvetica,Arial" font-size="10" fill="#737373"
text-anchor="end">0.3 X</text>
<line x1="100" y1="42" x2="118" y2="42" stroke="#969696"/>
<line x1="100" y1="47" x2="118" y2="47" stroke="#969696"/>
<text x="124" y="48" font-family="Helvetica,Arial" font-size="10" fill="#737373">0.10 X</text>
<line x1="290" y1="63" x2="290" y2="97" stroke="#969696"/>
<text x="298" y="84" font-family="Helvetica,Arial" font-size="10" fill="#737373">X = font size</text>
</svg></div></div>
<h2 style="margin-top:44px">Logo</h2>
<p class="lead">Download the files from the repository — SVG for screen, PNG for quick placement,
PDF for print.</p>
<div style="background:#f0f0f0;padding:24px;margin-bottom:26px;text-align:center">
<img src="{RAW}/svg/binder-logo.svg" width="300" alt="BINDER logo"></div>
<table><tr><th>Variant</th><th>Files</th></tr>
<tr><td><strong>Red and black</strong> — the standard version</td>
<td><a href="{RAW}/svg/binder-logo.svg">SVG</a> · <a href="{RAW}/png/binder-logo.png">PNG</a> ·
<a href="{RAW}/pdf/binder-logo.pdf">PDF</a> &nbsp;|&nbsp; with claim:
<a href="{RAW}/png/binder-logo-claim.png">PNG</a> ·
<a href="{RAW}/pdf/binder-logo-claim.pdf">PDF</a></td></tr>
<tr><td><strong>Solid black</strong></td>
<td><a href="{RAW}/svg/binder-logo-black.svg">SVG</a> ·
<a href="{RAW}/png/binder-logo-black.png">PNG</a> &nbsp;|&nbsp; with claim:
<a href="{RAW}/svg/binder-logo-black-claim.svg">SVG</a></td></tr>
<tr><td><strong>Solid white</strong> — for dark backgrounds</td>
<td><a href="{RAW}/svg/binder-logo-white.svg">SVG</a> ·
<a href="{RAW}/png/binder-logo-white.png">PNG</a> &nbsp;|&nbsp; with claim:
<a href="{RAW}/svg/binder-logo-white-claim.svg">SVG</a> ·
<a href="{RAW}/png/binder-logo-white-claim.png">PNG</a></td></tr>
<tr><td><strong>Red and white</strong> — for dark backgrounds</td>
<td><a href="{RAW}/svg/binder-logo-red-white.svg">SVG</a> &nbsp;|&nbsp; with claim:
<a href="{RAW}/svg/binder-logo-red-white-claim.svg">SVG</a></td></tr>
<tr><td><strong>Bildmarke only</strong> — favicons</td>
<td><a href="{RAW}/png/binder-icon.png">PNG</a></td></tr></table>
<div class="two" style="margin-top:26px"><div><h3>Clear space and position</h3>
<p style="font-size:14px">The measure is <strong>X, the height of the Bildmarke</strong>. Keep
<strong>1.5 × X</strong> clear on all sides. Place the logo <strong>top right, 2 × X from the format
edge</strong>. The positioning distance is not the clear space; observe both.</p>
<svg viewBox="0 0 300 190" width="100%" style="border:1px solid #cdcdcd;background:#fff"
role="img" aria-label="Diagram of logo clear space">
<rect x="1" y="1" width="298" height="188" fill="none" stroke="#cdcdcd"/>
<rect x="168" y="42" width="102" height="44" fill="none" stroke="#e60000" stroke-dasharray="4 3"/>
<rect x="198" y="56" width="42" height="16" fill="#000"/>
<polygon points="186,56 198,56 192,72" fill="#e60000"/>
<polygon points="174,56 186,56 180,72" fill="#e60000"/>
<line x1="270" y1="20" x2="270" y2="42" stroke="#969696"/>
<text x="276" y="34" font-family="Helvetica,Arial" font-size="9" fill="#737373">2 X</text>
<text x="219" y="100" font-family="Helvetica,Arial" font-size="9" fill="#e60000"
text-anchor="middle">clear space 1.5 X</text>
<line x1="174" y1="80" x2="174" y2="86" stroke="#969696"/>
<text x="150" y="86" font-family="Helvetica,Arial" font-size="9" fill="#737373"
text-anchor="end">X = height</text></svg></div>
<div><h3>Minimum sizes</h3>
<table><tr><th>Version</th><th>Minimum</th></tr>
<tr><td>Logo <strong>with</strong> claim</td><td>30 mm</td></tr>
<tr><td>Logo <strong>without</strong> claim</td><td>20 mm</td></tr>
<tr><td>Bildmarke alone</td><td>5 mm</td></tr></table>
<p style="font-size:14px;color:#737373">Below 30 mm width, drop the claim — it is no longer
legible.</p>
<h3>Never</h3><ul class="rules">
<li>Use the word mark without the Bildmarke</li>
<li>Replace the typeface</li>
<li>Crop, compress, distort or rotate it</li>
<li>Add further elements to it</li>
<li>Recolour it beyond black, white or full colour</li>
<li>Use the Bildmarke as a bullet, watermark or decoration</li></ul></div></div></section>"""


def main():
    print("Generating from tokens/colors.json:")
    build_css()
    build_scss()
    build_swatch([{**v, "label": LABELS[k]} for k, v in PRIMARY.items()], "assets/primary.svg")
    build_swatch(P["redShades"], "assets/shades-red.svg")
    build_swatch(P["blackShades"], "assets/shades-black.svg")
    build_swatch(P["chart"], "assets/chart.svg", cell=76)
    build_markdown()
    build_page()


if __name__ == "__main__":
    main()
