#!/usr/bin/env python3
"""Generate the derived artefacts from tokens/colors.json.

Run after changing a value so the CSS, Sass, swatches, colors.md and the
published page stay in step:

    python3 tools/build.py
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
P = json.loads((ROOT / "tokens/colors.json").read_text())
PRIMARY = P["primary"]
GRAYS, REDS = P["grayScale"], P["redScale"]
LABELS = {"white": "White", "gray100": "Gray 100", "gray300": "Gray 300", "gray500": "Gray 500",
          "gray800": "Gray 800", "black": "Black", "binderRed": "BINDER Red",
          "redDark": "Red Dark"}


def srgb(c):
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def lstar(hexv):
    h = hexv.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    y = 0.2126 * srgb(r) + 0.7152 * srgb(g) + 0.0722 * srgb(b)
    return 116 * y ** (1 / 3) - 16 if y > 0.008856 else 903.3 * y


def is_light(hexv):
    return lstar(hexv) > 55


def refs(v):
    return ", ".join(x for x in (v.get("hks"), v.get("pantone"), v.get("ral")) if x) or "—"


def write(rel, text):
    (ROOT / rel).write_text(text)
    print(f"  {rel}")


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def build_css():
    o = [":root {", "  /* BINDER corporate colours — generated by tools/build.py", "",
         "     Nine grays, 100 (lightest) to 900 (darkest), the same direction as CSS",
         "     font-weight. White and black sit outside the ramp, as in Bootstrap. */", ""]
    for row in GRAYS:
        key = f"gray-{row['scale']}" if row["scale"] else slug(row["name"])
        o.append(f"  --binder-{key}: {row['hex']};")
    o += ["", "  /* Reds. BINDER Red and Red Dark are brand colours, not ramp steps. */"]
    for row in REDS:
        key = f"red-{row['scale']}" if row["scale"] else slug(row["name"])
        o.append(f"  --binder-{key}: {row['hex']};")
    o += ["", "  /* Sustainability topics */", f"  --binder-green: {P['green']['hex']};",
          "", "  /* Chart colours A–L */"]
    o += [f"  --binder-chart-{c['key'].lower()}: {c['hex']};" for c in P["chart"]]
    o.append("}")
    write("tokens/colors.css", "\n".join(o) + "\n")


def build_scss():
    o = ["// BINDER corporate colours — generated by tools/build.py", "",
         "// White and black sit outside the ramp, as in Bootstrap.",
         f"$white:      {GRAYS[0]['hex']};"]
    o += [f"$gray-{r['scale']}:   {r['hex']};"
          for r in GRAYS if r["scale"]]
    o += [f"$black:      {GRAYS[-1]['hex']};", ""]
    o += ["", "// Reds"]
    for row in REDS:
        name = f"$red-{row['scale']}:" if row["scale"] else f"${slug(row['name'])}:"
        o.append(name.ljust(14) + f"{row['hex']};" )
    o += ["", "$binder-green: " + f"{P['green']['hex']};", "", "// Chart colours A–L"]
    o += [f"$chart-{c['key'].lower()}:".ljust(14) + f"{c['hex']};" for c in P["chart"]]
    write("tokens/colors.scss", "\n".join(o) + "\n")


def build_swatch(rows, rel, cell=110, height=104):
    width = cell * len(rows)
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
         f'viewBox="0 0 {width} {height}" role="img">',
         f'<rect width="{width}" height="{height}" fill="#ffffff"/>']
    for i, row in enumerate(rows):
        x, hexv = i * cell, row["hex"]
        label = row.get("label") or row.get("key") or ""
        o += [f'<rect x="{x+4}" y="4" width="{cell-8}" height="56" fill="{hexv}" '
              f'stroke="#cdcdcd" stroke-width="1"/>',
              f'<text x="{x+cell//2}" y="76" text-anchor="middle" '
              f'font-family="Arial,Helvetica,sans-serif" font-size="11" font-weight="bold" '
              f'fill="#000000">{label}</text>',
              f'<text x="{x+cell//2}" y="92" text-anchor="middle" '
              f'font-family="Arial,Helvetica,sans-serif" font-size="10" fill="#737373">{hexv}</text>']
    o.append("</svg>")
    write(rel, "\n".join(o) + "\n")


def build_markdown():
    md = ["# Colours", "",
          "The BINDER appearance rests on a triad of **black, white and BINDER Red**. This triad is",
          "the core of the corporate design and a primary design element in its own right.",
          "Everything else supports it and must never dilute its contrast.", "",
          "Machine-readable versions live in [tokens/](tokens/): [`colors.json`](tokens/colors.json),",
          "[`colors.css`](tokens/colors.css) and [`colors.scss`](tokens/colors.scss).", "",
          "**Hex values apply to screen, CMYK values apply to print.** The grays carry a slight blue",
          "cast on screen but print as pure K with no CMY component: converted exactly, the cast",
          "comes to under 6 % cyan, and cyan that low cannot be reproduced reliably in offset",
          "printing. Use hex on screen and CMYK on paper.", "",
          "## Primary colours", "", "![Primary colours](assets/primary.svg)", "",
          "| Colour | Hex | CMYK | Print references | Use |", "|---|---|---|---|---|"]
    for k, v in PRIMARY.items():
        md.append(f"| **{LABELS[k]}** | `{v['hex']}` | {v['cmyk']} | {refs(v)} | {v['use']} |")

    md += ["", "## The gray scale", "", "![Gray scale](assets/scale-gray.svg)", "",
           "The scale runs 100 (lightest) to 900 (darkest), the same direction as CSS",
           "`font-weight`.", "",
           "White and black carry no number. They sit outside the ramp, exactly as `$white` and",
           "`$black` do in Bootstrap and Tailwind: a `0` would read as `#000`, which is black.", "",
           "| Colour | Hex | CMYK |", "|---|---|---|"]
    md += [f"| {r['name']} | `{r['hex']}` | {r['cmyk']} |" for r in GRAYS]
    md += ["", "The ramp is denser at the light end on purpose: pale surface tones get used over",
           "large areas, where small differences matter. The dark half steps more widely, because",
           "the eye separates dark tones less well anyway.", "",
           "## The red scale", "", "![Red scale](assets/scale-red.svg)", "",
           "| Colour | Hex | CMYK |", "|---|---|---|"]
    md += [f"| {r['name']} | `{r['hex']}` | {r['cmyk']} |" for r in REDS]
    md += ["", "BINDER Red and Red Dark carry no number - they are brand colours, not ramp steps.",
           "", "**Red Dark** is the accent alongside BINDER Red: a calm, high-grade colour for",
           "restrained emphasis in graphics and icons, and the mouseover state of a red button.", "",
           "## BINDER Green", "", f"`{P['green']['hex']}` - CMYK {P['green']['cmyk']}", "",
           "For **sustainability and eco topics** (BINDER goes green). Not a general-purpose",
           "accent - using it elsewhere weakens the black/white/red triad.", "",
           "## Chart colours", "", "![Chart colours](assets/chart.svg)", "",
           "| Key | Hex | CMYK |", "|---|---|---|"]
    md += [f"| {c['key']} | `{c['hex']}` | {c['cmyk']} |" for c in P["chart"]]
    md += ["", "### Which colours for how many values", "",
           "Do not pick freely - take the prescribed sequence for the number of values in your",
           "chart. This keeps charts recognisable across all BINDER media.", "",
           "| Values | Sequence |", "|---|---|"]
    md += [f"| {n} | {' - '.join(P['chartSequences'][n])} |"
           for n in sorted(P["chartSequences"], key=int)]
    md += ["", "Text inside charts follows the same rule as everywhere else: never below 6 pt.",
           "See [typography.md](typography.md).", ""]
    write("colors.md", "\n".join(md))


def cell(label, hexv, cmyk, scale=None, extra=""):
    cls = "light" if is_light(hexv) else ""
    num = f'<span class="n">{scale}</span>' if scale else ""
    return (f'<button class="sw {cls}" style="background:{hexv}" data-hex="{hexv}">'
            f'<span class="nm">{label}{num}</span>'
            f'<span class="cd">{hexv}<br>{cmyk}{extra}</span></button>')


PAGE_CSS = """
:root{--w:#fff;--g10:#f0f0f0;--g25:#cdcdcd;--g45:#969696;--g65:#737373;--red:#e60000;--k:#000}
*{box-sizing:border-box}
body{margin:0;background:var(--g10);color:var(--k);font:15px/1.6 "Source Sans 3","Helvetica Neue",Arial,sans-serif}
.wrap{max-width:1180px;margin:0 auto;background:var(--w);min-height:100vh;box-shadow:0 0 40px rgba(0,0,0,.07)}
header{padding:56px 44px 40px;border-bottom:1px solid var(--g25)}
.rule{width:58px;height:6px;background:var(--red);margin-bottom:18px}
h1{margin:0;font-size:38px;line-height:1.1;font-weight:600;letter-spacing:-.02em}
header p{margin:12px 0 0;color:var(--g65);font-size:17px;max-width:62ch}
header .meta{margin-top:20px;font-size:13px;color:var(--g65)}
header a{color:var(--red);text-decoration:none;border-bottom:1px solid rgba(230,0,0,.3)}
section{padding:44px}section+section{border-top:1px solid var(--g25)}
h2{font-size:25px;margin:0 0 6px;font-weight:600;letter-spacing:-.01em;position:relative;padding-top:14px}
h2::before{content:"";position:absolute;top:0;left:0;width:2.6ch;height:2.5px;background:var(--red)}
h3{font-size:16px;margin:34px 0 10px;font-weight:600}
.lead{color:var(--g65);margin:0 0 26px;max-width:70ch}
.grid{display:grid;gap:2px;background:var(--g25);border:1px solid var(--g25)}
.c4{grid-template-columns:repeat(4,1fr)}.c5{grid-template-columns:repeat(5,1fr)}
.c8{grid-template-columns:repeat(8,1fr)}.c11{grid-template-columns:repeat(11,1fr)}
.c11 .sw,.c12 .sw{height:104px}.c8 .sw{height:118px}
.c11 .sw .cd,.c12 .sw .cd{font-size:8.5px}.c11 .sw .nm,.c8 .sw .nm{font-size:11px}
.c12{grid-template-columns:repeat(12,1fr)}
.sw{height:132px;border:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;
 color:#fff;cursor:pointer;font:inherit;padding:8px;text-align:center;position:relative;transition:transform .18s ease}
.sw.light{color:var(--k)}
.sw:hover{transform:scale(1.06);z-index:5;box-shadow:0 6px 22px rgba(0,0,0,.28)}
.sw .nm{font-size:12px;font-weight:600;line-height:1.2}
.sw .n{display:block;font-weight:400;opacity:.72;font-size:10px;margin-top:1px}
.sw .cd{font-size:9.5px;opacity:.88;line-height:1.4}
.sw.copied::after{content:"copied";position:absolute;top:6px;right:6px;background:var(--red);color:#fff;font-size:9px;padding:2px 5px;border-radius:2px}
table{border-collapse:collapse;width:100%;font-size:14px;margin:14px 0}
th,td{text-align:left;padding:9px 12px;border-bottom:1px solid var(--g25)}
th{background:var(--g10);font-weight:600;font-size:13px}
code{background:var(--g10);padding:1px 6px;border-radius:3px;font-size:13px}
.note{border-left:4px solid var(--red);background:var(--g10);padding:16px 20px;margin:22px 0;max-width:78ch}
.note strong{display:block;margin-bottom:4px}
.specimen{border:1px solid var(--g25);padding:30px 34px;margin:16px 0}
.specimen div{margin:0 0 14px}
.tag{font-size:11px;color:var(--g45);font-weight:400;margin-left:10px}
.two{display:grid;grid-template-columns:1fr 1fr;gap:30px}
ul.rules{font-size:14px;line-height:1.75;padding-left:20px}
footer{padding:34px 44px 50px;border-top:1px solid var(--g25);font-size:13px;color:var(--g65)}
footer a{color:var(--red)}
.seqrow span{display:inline-block;width:16px;height:16px;margin-right:3px;vertical-align:-3px;border-radius:2px}
@media(max-width:820px){.two{grid-template-columns:1fr}
 .c4,.c5,.c8{grid-template-columns:repeat(4,1fr)}.c11,.c12{grid-template-columns:repeat(6,1fr)}
 .sw{height:110px}
 .c12{grid-template-columns:repeat(6,1fr)}section{padding:30px 22px}header{padding:38px 22px 30px}h1{font-size:29px}}
"""

RAW = "https://raw.githubusercontent.com/Binder-GmbH/binder-corporate-design/main/logo"


def build_page():
    h = ['<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">',
         '<meta name="viewport" content="width=device-width,initial-scale=1">',
         '<title>BINDER Corporate Design</title>',
         f'<style>{PAGE_CSS}</style></head><body><div class="wrap">',
         '<header><div class="rule"></div><h1>BINDER Corporate Design</h1>',
         '<p>Colours, typography and logo rules for anyone producing material in the BINDER '
         'design — agencies, partners, suppliers and integrators.</p>',
         '<div class="meta"><a href="https://github.com/Binder-GmbH/binder-corporate-design">'
         'Repository on GitHub</a> · Click any colour to copy its hex value</div></header>',
         '<section><h2>The triad</h2><p class="lead">Black, white and BINDER Red produce the '
         'primary BINDER colour impression. This triad is the core of the corporate design and a '
         'primary design element in its own right. Everything else supports it and must never '
         'dilute its contrast.</p><div class="grid c8">']
    for k, v in PRIMARY.items():
        h.append(cell(LABELS[k], v["hex"], v["cmyk"]))
    h.append('</div><table><tr><th>Colour</th><th>Hex</th><th>CMYK</th>'
             '<th>Print references</th><th>Use</th></tr>')
    for k, v in PRIMARY.items():
        h.append(f'<tr><td><strong>{LABELS[k]}</strong></td>'
                 f'<td><code>{v["hex"]}</code></td><td>{v["cmyk"]}</td><td>{refs(v)}</td>'
                 f'<td>{v["use"]}</td></tr>')
    h.append('</table>')

    h.append('<h3>Gray scale <span class="tag">100 lightest &middot; 900 darkest &middot; white '
             'and black sit outside the ramp</span></h3><div class="grid c11">')
    for r in GRAYS:
        h.append(cell(r["name"], r["hex"], r["cmyk"]))
    h.append('</div><p class="cap">The scale runs 100 (lightest) to 900 (darkest), the same '
             'direction as CSS font-weight. It is denser at the light end on purpose: pale surface '
             'tones get used over large areas, where small differences matter.</p>')

    h.append('<h3>Red scale <span class="tag">BINDER Red and Red Dark are brand colours, not ramp '
             'steps</span></h3><div class="grid c5">')
    for r in REDS:
        h.append(cell(r["name"], r["hex"], r["cmyk"]))
    h.append('</div>')

    h.append('<h3>BINDER Green <span class="tag">sustainability and eco topics</span></h3>'
             '<div class="grid c4">')
    h.append(cell("BINDER Green", P["green"]["hex"], P["green"]["cmyk"]))
    h.append('<div style="grid-column:span 3;background:#fff;padding:22px;color:#737373;'
             'font-size:14px;display:flex;align-items:center">For sustainability and eco topics '
             '(BINDER goes green). Not a general-purpose accent, using it elsewhere weakens the '
             'black/white/red triad.</div></div>')

    h.append('<h3>Chart colours</h3><div class="grid c12">')
    for c in P["chart"]:
        h.append(cell(c["key"], c["hex"], c["cmyk"]))
    h.append('</div><p class="cap">Do not pick freely, use the prescribed sequence for the number '
             'of values in your chart.</p>'
             '<table class="seqrow"><tr><th>Values</th><th>Sequence</th></tr>')
    for n in sorted(P["chartSequences"], key=int):
        seq = P["chartSequences"][n]
        sws = "".join(f'<span style="background:'
                      f'{[c["hex"] for c in P["chart"] if c["key"] == k][0]}"></span>' for k in seq)
        h.append(f'<tr><td><strong>{n}</strong></td><td>{sws} &nbsp;{" &middot; ".join(seq)}</td></tr>')
    h.append('</table></section>')
    h.append(TYPO_SECTION)
    h.append(LOGO_SECTION)
    h.append('<footer><strong>BINDER GmbH Corporate Design</strong> · '
             '<a href="https://github.com/Binder-GmbH/binder-corporate-design">Repository</a> · '
             '<a href="mailto:marketing@binder-world.com">marketing@binder-world.com</a>'
             '<p>The BINDER name, logo and word/figurative marks are protected trademarks of '
             'BINDER GmbH. These guidelines are published for legitimate use by press, partners, '
             'suppliers and integrators. They transfer no rights in the marks themselves.</p>'
             '</footer></div>'
             '<script>document.querySelectorAll(".sw").forEach(function(b){'
             'b.addEventListener("click",function(){navigator.clipboard.writeText(b.dataset.hex);'
             'b.classList.add("copied");setTimeout(function(){b.classList.remove("copied")},1100);'
             '});});</script></body></html>')
    write("docs/index.html", "\n".join(h))


TYPO_SECTION = """<section><h2>Typography</h2>
<p class="lead">The corporate typeface is <strong>Source Sans 3</strong>, designed by Paul D. Hunt.
It is <strong>open source and free to use</strong> — no licence has to be purchased. Get it from
<a href="https://fonts.google.com/specimen/Source+Sans+3">Google Fonts</a>,
<a href="https://fonts.adobe.com/fonts/source-sans">Adobe Fonts</a> or
<a href="https://github.com/adobe-fonts/source-sans">GitHub</a>. This page is set in it.</p>
<div class="two"><div>
<p style="font-size:14px;color:#737373">Weights in use: Light 300, Regular 400, Medium 500,
SemiBold 600.</p>
<h3>Source Serif 4 <span class="tag">for quotations and emotional text</span></h3>
<p style="font-size:14px">The serif companion. Same origin as Source Sans 3, also open source and
free: <a href="https://fonts.google.com/specimen/Source+Serif+4">Google Fonts</a>,
<a href="https://fonts.adobe.com/fonts/source-serif">Adobe Fonts</a>,
<a href="https://github.com/adobe-fonts/source-serif">GitHub</a>.</p>
<h3>Substitutes</h3>
<table><tr><th>Instead of</th><th>Use</th><th>When</th></tr>
<tr><td>Source Sans 3</td><td><strong>Arial Unicode MS</strong></td><td>Office applications and Word
templates; also covers Chinese characters</td></tr>
<tr><td>Source Serif 4</td><td><strong>Georgia</strong></td><td>Quotations in substitute
settings</td></tr></table>
<h3>Rules</h3><ul class="rules">
<li>Primary text colour is <strong>100&nbsp;% black</strong>. BINDER Red for emphasis, grays to
de-emphasise. White on red or dark backgrounds.</li>
<li><strong>Minimum size 6&nbsp;pt</strong> — including text inside charts and diagrams.</li>
<li>Kerning: <strong>optical</strong>.</li>
<li>Old-style figures in body copy, lining figures in headlines, tabular figures in tables.</li>
</ul></div><div>
<h3>Hierarchy <span class="tag">A4; scale other formats proportionally</span></h3>
<table><tr><th>Level</th><th>Weight</th><th>Size / leading</th></tr>
<tr><td>H1</td><td>SemiBold</td><td>22 / 27.5 pt</td></tr>
<tr><td>Subline</td><td>Light</td><td>22 / 27.5 pt</td></tr>
<tr><td>H2</td><td>Medium</td><td>15 / 16.5 pt</td></tr>
<tr><td>H3</td><td>SemiBold, caps</td><td>10 / 11 pt</td></tr>
<tr><td>H4</td><td>SemiBold</td><td>9 / 11 pt</td></tr>
<tr><td>Body</td><td>Regular</td><td>8 / 11 pt</td></tr>
<tr><td>Lists</td><td>Light</td><td>8 / 11 pt</td></tr>
<tr><td>Captions</td><td>Light</td><td>7 / 11 pt</td></tr>
<tr><td>Running head</td><td>SemiBold + Light</td><td>8 pt, 65&nbsp;% black</td></tr></table>
<p style="font-size:14px;color:#737373"><strong>Exception</strong> — product catalogue and price
list: H1 SemiBold 18 / 22 pt, subline Light 18 / 22 pt.</p></div></div>
<h3>Specimen</h3>
<div class="specimen">
<div style="font-size:31px;font-weight:600;line-height:1.25">Best conditions for your success</div>
<div style="font-size:31px;font-weight:300;line-height:1.25;color:#737373">A subline goes into more
detail than the headline above it</div>
<div style="font-size:21px;font-weight:500">Heading level two introduces a section</div>
<div style="font-size:14px;font-weight:600;text-transform:uppercase;letter-spacing:.07em">Heading
level three, set in caps</div>
<div style="font-size:13px;max-width:62ch">Body copy carries the argument. Structure the content
before you set it: every topic needs exactly one clearly most important headline, and levels may be
skipped where they are not needed.</div>
<div style="font-size:11px;font-weight:300;color:#737373">Captions are set only where they add
something the image does not already say.</div>
<div style="font-family:'Source Serif 4',Georgia,serif;font-size:19px;font-style:italic;
line-height:1.45;color:#000;border-left:3px solid #e60000;padding-left:16px;margin-top:22px">
&ldquo;Emotional text such as quotations is set in Source Serif 4.&rdquo;</div></div>
<div class="note"><strong>On the serif face.</strong> The manual names Source Sans 3 at this point,
which is a sans-serif and cannot be the serif face it describes in the same sentence — a leftover
from replacing the previous typeface throughout the document. Source Serif 4 is the counterpart to
Source Sans 3 and is used here on that basis; confirmation from marketing is pending.</div>
</section>"""


LOGO_SECTION = f"""<section><h2>The red line above titles</h2>
<p class="lead">A short horizontal red line sits directly above main titles. All three measurements
derive from the font size, so the rule holds at any scale.</p>
<div class="two"><div><table><tr><th>Property</th><th>Rule</th></tr>
<tr><td>Colour</td><td>BINDER Red</td></tr>
<tr><td>Placement</td><td>Directly above the title, always flush left</td></tr>
<tr><td>Thickness</td><td><strong>0.10 ×</strong> font size</td></tr>
<tr><td>Length</td><td>Width of the <strong>first three letters</strong> of the title</td></tr>
<tr><td>Distance to title</td><td><strong>0.3 ×</strong> font size</td></tr></table>
<p style="font-size:14px;color:#737373">At 50 pt type: thickness 5 pt, distance 16.6 pt.</p></div>
<div><svg viewBox="0 0 380 150" width="100%" style="border:1px solid #cdcdcd;background:#fff"
role="img" aria-label="Diagram of the red line rule">
<rect x="40" y="42" width="52" height="5" fill="#e60000"/>
<text x="40" y="97" font-family="Helvetica,Arial" font-size="42" font-weight="bold"
fill="#000">Incubator</text>
<line x1="40" y1="30" x2="92" y2="30" stroke="#969696"/>
<text x="66" y="25" font-family="Helvetica,Arial" font-size="10" fill="#737373"
text-anchor="middle">first 3 letters</text>
<line x1="26" y1="47" x2="26" y2="63" stroke="#969696"/>
<text x="20" y="58" font-family="Helvetica,Arial" font-size="10" fill="#737373"
text-anchor="end">0.3 X</text>
<line x1="100" y1="42" x2="118" y2="42" stroke="#969696"/>
<line x1="100" y1="47" x2="118" y2="47" stroke="#969696"/>
<text x="124" y="48" font-family="Helvetica,Arial" font-size="10" fill="#737373">0.10 X</text>
<line x1="290" y1="63" x2="290" y2="97" stroke="#969696"/>
<text x="298" y="84" font-family="Helvetica,Arial" font-size="10" fill="#737373">X = font size</text>
</svg></div></div>
<h2 style="margin-top:44px">Logo</h2>
<p class="lead">Download the files from the repository — SVG for screen, PNG for quick placement,
PDF for print.</p>
<div style="background:#f0f0f0;padding:24px;margin-bottom:26px;text-align:center">
<img src="{RAW}/svg/binder-logo.svg" width="300" alt="BINDER logo"></div>
<table><tr><th>Variant</th><th>Files</th></tr>
<tr><td><strong>Red and black</strong> — the standard version</td>
<td><a href="{RAW}/svg/binder-logo.svg">SVG</a> · <a href="{RAW}/png/binder-logo.png">PNG</a> ·
<a href="{RAW}/pdf/binder-logo.pdf">PDF</a> &nbsp;|&nbsp; with claim:
<a href="{RAW}/png/binder-logo-claim.png">PNG</a> ·
<a href="{RAW}/pdf/binder-logo-claim.pdf">PDF</a></td></tr>
<tr><td><strong>Solid black</strong></td>
<td><a href="{RAW}/svg/binder-logo-black.svg">SVG</a> ·
<a href="{RAW}/png/binder-logo-black.png">PNG</a> &nbsp;|&nbsp; with claim:
<a href="{RAW}/svg/binder-logo-black-claim.svg">SVG</a></td></tr>
<tr><td><strong>Solid white</strong> — for dark backgrounds</td>
<td><a href="{RAW}/svg/binder-logo-white.svg">SVG</a> ·
<a href="{RAW}/png/binder-logo-white.png">PNG</a> &nbsp;|&nbsp; with claim:
<a href="{RAW}/svg/binder-logo-white-claim.svg">SVG</a> ·
<a href="{RAW}/png/binder-logo-white-claim.png">PNG</a></td></tr>
<tr><td><strong>Red and white</strong> — for dark backgrounds</td>
<td><a href="{RAW}/svg/binder-logo-red-white.svg">SVG</a> &nbsp;|&nbsp; with claim:
<a href="{RAW}/svg/binder-logo-red-white-claim.svg">SVG</a></td></tr>
<tr><td><strong>Bildmarke only</strong> — favicons</td>
<td><a href="{RAW}/png/binder-icon.png">PNG</a></td></tr></table>
<div class="two" style="margin-top:26px"><div><h3>Clear space and position</h3>
<p style="font-size:14px">The measure is <strong>X, the height of the Bildmarke</strong>. Keep
<strong>1.5 × X</strong> clear on all sides. Place the logo <strong>top right, 2 × X from the format
edge</strong>. The positioning distance is not the clear space; observe both.</p>
<svg viewBox="0 0 1180 520" width="100%" role="img"
aria-label="Logo clear space and positioning">
<g font-family="'Source Sans 3',Helvetica,Arial,sans-serif">
  <rect width="1180" height="520" fill="#fff"/>

  <!-- Format -->
  <rect x="250" y="60" width="840" height="364" fill="none" stroke="#cdcdcd" stroke-width="1.6"/>
  <text x="250" y="44" font-size="18" fill="#737373">format edge</text>

  <!-- Schutzraum -->
  <rect x="319.4" y="95.7" width="734.9" height="285.4"
        fill="#e60000" fill-opacity=".05" stroke="#e60000" stroke-width="1.5" stroke-dasharray="9 6"/>

  <!-- das echte Logo -->
  <g transform="translate(380.88 167.26)">
  <path d="M118.03,44.59h48.88c8.74,0,12.86,2.83,12.86,10.55v6.56c0,5.01-3.35,8.23-9.26,9.26,6.17,1.03,9.65,4.89,9.65,10.42v6.95c0,7.2-5.66,10.68-16.85,10.68h-45.28v-54.41h0ZM131.14,75.33v13.89h29.71c4.5,0,6.43-.9,6.43-4.89v-4.11c0-3.99-1.93-4.89-6.43-4.89h-29.71ZM131.14,53.46v12.86h29.71c3.99,0,5.92-.64,5.92-3.86v-5.15c0-3.21-1.8-3.86-5.92-3.86h-29.71Z" fill="#231f20"/>
  <polygon points="202.57 44.59 215.81 44.59 215.81 99 202.57 99 202.57 44.59 202.57 44.59" fill="#231f20"/>
  <polygon points="240 44.59 249.13 44.59 295.31 80.73 295.31 44.59 307.27 44.59 307.27 99 298.14 99 252.09 62.34 252.09 99 240 99 240 44.59 240 44.59" fill="#231f20"/>
  <path d="M331.54,44.59h36.66c21.48,0,32.67,10.16,32.67,27.01,0,18.4-12.09,27.4-36.01,27.4h-33.32v-54.41h0ZM362.03,88.84c16.85,0,25.21-3.73,25.21-17.88,0-11.32-6.31-16.59-18.91-16.59h-23.41v34.47h17.11Z" fill="#231f20"/>
  <polygon points="420.86 44.59 479.26 44.59 479.26 54.24 434.23 54.24 434.23 66.07 460.48 66.07 460.48 75.46 434.23 75.46 434.23 88.84 479.89 88.84 479.89 99 420.86 99 420.86 44.59 420.86 44.59" fill="#231f20"/>
  <path d="M498.99,44.59h49.01c8.75,0,12.73,2.96,12.73,10.55v12.86c0,7.46-3.99,10.42-12.73,10.42h-7.47l25.86,20.58h-19.03l-22.77-20.58h-12.48v20.58h-13.12v-54.41h0ZM512.11,53.98v15.05h30.22c3.99,0,6.05-.77,6.05-4.37v-6.3c0-3.6-2.06-4.38-6.05-4.38,0,0-30.22,0-30.22,0Z" fill="#231f20"/>
  <polygon points="70.05 56.24 95.94 71.2 70.05 86.14 70.05 56.24 70.05 56.24" fill="#ed1c24"/>
  <polygon points="45.6 35.46 71.49 50.4 45.6 65.35 45.6 35.46 45.6 35.46" fill="#ed1c24"/>
  <polygon points="45.6 76.92 71.49 91.87 45.6 106.82 45.6 76.92 45.6 76.92" fill="#ed1c24"/>
  </g>

  <!-- Hilfslinien nach links -->
  <line x1="204" y1="202.71999999999997" x2="420.48" y2="202.71999999999997" stroke="#737373" stroke-width="0.8" stroke-dasharray="4 4"/>
  <line x1="204" y1="274.0799999999999" x2="420.48" y2="274.0799999999999" stroke="#737373" stroke-width="0.8" stroke-dasharray="4 4"/>
  <line x1="204" y1="381.1199999999999" x2="313.44000000000005" y2="381.1199999999999" stroke="#737373" stroke-width="0.8" stroke-dasharray="4 4"/>

  <!-- X und 1.5 X, links aussen -->
  <line x1="204" y1="202.71999999999997" x2="204" y2="274.0799999999999" stroke="#737373" stroke-width="1.5"/><line x1="196" y1="202.71999999999997" x2="212" y2="202.71999999999997" stroke="#737373" stroke-width="1.5"/><line x1="196" y1="274.0799999999999" x2="212" y2="274.0799999999999" stroke="#737373" stroke-width="1.5"/><text x="190" y="245.39999999999995" text-anchor="end" font-size="20" fill="#737373">X</text>
  <line x1="204" y1="274.0799999999999" x2="204" y2="381.1199999999999" stroke="#737373" stroke-width="1.5"/><line x1="196" y1="274.0799999999999" x2="212" y2="274.0799999999999" stroke="#737373" stroke-width="1.5"/><line x1="196" y1="381.1199999999999" x2="212" y2="381.1199999999999" stroke="#737373" stroke-width="1.5"/><text x="190" y="334.5999999999999" text-anchor="end" font-size="20" fill="#737373">1.5 X</text>

  <!-- 2 X zur oberen und rechten Formatkante -->
  <line x1="1134" y1="60" x2="1134" y2="202.71999999999997" stroke="#737373" stroke-width="1.5"/><line x1="1126" y1="60" x2="1142" y2="60" stroke="#737373" stroke-width="1.5"/><line x1="1126" y1="202.71999999999997" x2="1142" y2="202.71999999999997" stroke="#737373" stroke-width="1.5"/><text x="1120" y="138.35999999999999" text-anchor="end" font-size="20" fill="#737373">2 X</text>
  <line x1="1090" y1="60" x2="1142" y2="60" stroke="#737373" stroke-width="0.8" stroke-dasharray="4 4"/>
  <line x1="947.28" y1="202.71999999999997" x2="1142" y2="202.71999999999997" stroke="#737373" stroke-width="0.8" stroke-dasharray="4 4"/>
  <line x1="947.28" y1="464" x2="1090" y2="464" stroke="#737373" stroke-width="1.5"/><line x1="947.28" y1="456" x2="947.28" y2="472" stroke="#737373" stroke-width="1.5"/><line x1="1090" y1="456" x2="1090" y2="472" stroke="#737373" stroke-width="1.5"/><text x="1018.64" y="490" text-anchor="middle" font-size="20" fill="#737373">2 X</text>
  <line x1="947.28" y1="282.0799999999999" x2="947.28" y2="472" stroke="#737373" stroke-width="0.8" stroke-dasharray="4 4"/>
  <line x1="1090" y1="424" x2="1090" y2="472" stroke="#737373" stroke-width="0.8" stroke-dasharray="4 4"/>

  <text x="319.44000000000005" y="411.1199999999999" font-size="19" fill="#e60000">clear space, 1.5 X on all sides</text>
  <text x="250" y="504" font-size="18" fill="#737373">X = the height of the Bildmarke</text>
</g></svg></div>
<div><h3>Minimum sizes</h3>
<table><tr><th>Version</th><th>Minimum</th></tr>
<tr><td>Logo <strong>with</strong> claim</td><td>30 mm</td></tr>
<tr><td>Logo <strong>without</strong> claim</td><td>20 mm</td></tr>
<tr><td>Bildmarke alone</td><td>5 mm</td></tr></table>
<p style="font-size:14px;color:#737373">Below 30 mm width, drop the claim — it is no longer
legible.</p>
<h3>Never</h3><ul class="rules">
<li>Use the word mark without the Bildmarke</li>
<li>Replace the typeface</li>
<li>Crop, compress, distort or rotate it</li>
<li>Add further elements to it</li>
<li>Recolour it beyond black, white or full colour</li>
<li>Use the Bildmarke as a bullet, watermark or decoration</li></ul></div></div></section>"""


def main():
    print("Generating from tokens/colors.json:")
    build_css()
    build_scss()
    build_swatch([{**v, "label": LABELS[k]} for k, v in PRIMARY.items()], "assets/primary.svg")
    build_swatch([{**r, "label": r["name"]} for r in GRAYS], "assets/scale-gray.svg", cell=100)
    build_swatch([{**r, "label": r["name"]} for r in REDS], "assets/scale-red.svg")
    build_swatch(P["chart"], "assets/chart.svg", cell=76)
    build_markdown()
    build_page()


if __name__ == "__main__":
    main()
